# permissions for end users to view openedxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openedx-viewer-role
rules:
- apiGroups:
  - cache.operatortrain.me
  resources:
  - openedxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.operatortrain.me
  resources:
  - openedxes/status
  verbs:
  - get
